### ISSUE TITLE
Tests fail with older astropy: astropy-helpers not in output

### ISSUE THREAD

**Issue by bnavigator** [astropy/pytest-astropy-header#12]
Trying to [package on OpenSUSE](https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:pytest/python-pytest-astropy-header), including Leap 15.2, which has some older versions.

From the [build log](https://build.opensuse.org/package/live_build_log/home:bnavigator:branches:devel:languages:python:pytest/python-pytest-astropy-header/openSUSE_Leap_15.2/x86_64):

```
[   56s] ============================= test session starts ==============================
[   56s] platform linux -- Python 3.6.9, pytest-5.2.4, py-1.8.0, pluggy-0.13.0
[   56s] 
[   56s] Running tests with Astropy version 2.0.3.
[   56s] Running tests in /tmp/pytest-of-abuild/pytest-0/test_override_package_multiple3.
[   56s] 
[   56s] Date: 2019-12-19T03:38:37
[   56s] 
[   56s] Platform: Linux-5.3.15-lp152.1-default-x86_64-with-glibc2.3.4
[   56s] 
[   56s] Executable: /usr/bin/python3
[   56s] 
[   56s] Full Python Version: 
[   56s] 3.6.9 (default, Sep 04 2019, 13:24:18) [GCC]
[   56s] 
[   56s] encodings: sys: utf-8, locale: ANSI_X3.4-1968, filesystem: ascii
[   56s] byteorder: little
[   56s] float info: dig: 15, mant_dig: 15
[   56s] 
[   56s] Package versions: 
[   56s] numpy: 1.17.4
[   56s] pandas: not available
[   56s] 
[   56s] 
[   56s] rootdir: /tmp/pytest-of-abuild/pytest-0/test_override_package_multiple3
[   56s] plugins: astropy-header-0.1.2, cov-2.5.1
[   56s] collected 0 items
```

All tests fail because they look for a line with astropy-helpers, which is not present. I [patched](https://build.opensuse.org/package/view_file/home:bnavigator:branches:devel:languages:python:pytest/python-pytest-astropy-header/debug-test.patch?expand=1) the test script to debug the AssertionError:

```
[   56s]         lines = extract_package_version_lines(out)
[   56s]         try:
[   56s]             assert len(lines) == 6
[   56s]             assert lines[0].startswith('Numpy: ')
[   56s]             assert lines[1].startswith('Scipy: ')
[   56s]             assert lines[2].startswith('Matplotlib: ')
[   56s]             assert lines[3].startswith('h5py: ')
[   56s]             assert lines[4].startswith('scikit-image: ')
[   56s]             assert lines[5].startswith('astropy-helpers: ')
[   56s]             assert 'Running tests with fakepackage version 1.0.2' in out
[   56s]         except AssertionError as e:
[   56s] >           raise Exception(lines)
[   56s] E           Exception: ['Numpy: 1.17.4', 'Scipy: not available', 'Matplotlib: not available', 'h5py: not available', 'scikit-image: not available']
```

Does this mean astropy>=0.3 is required and Leap 15.2 miss out, or can this be fixed?

**Comment by pllim** [comment]
Astropy version 2.0.3 is pretty old. With 4.0 out, I think it is officially not supported anymore. Try upgrading?

**Comment by bnavigator** [comment]
Yeah I don't know why Leap 15.2 comes with such an old version.  Strangely enough the older Leap 15.1 has a newer astropy.

I upped the requirement to `astropy >= 3.0`. Maybe you should mention that in your setup.cfg as well.

**Comment by pllim** [comment]
`astropy` is not a required dependency of this package. Where do you think this should be mentioned so that it is obvious to end user?

**Comment by bnavigator** [comment]
It is required for the unit tests:
https://github.com/astropy/pytest-astropy-header/blob/210f926ffe5b093f11aebc03dae3d253a191a280/setup.cfg#L25-L32

**Comment by pllim** [comment]
As per #32 , older astropy (`<4)` is no longer supported. We apologize for any inconvenience caused.
