### ISSUE TITLE
[astropy] CI fails on fork due to astropy version check here

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-astropy-header#31]
Workflow:

* Push changes to `astropy` fork.
* Wait for GitHub Actions to pass on fork without relying on upstream.

What happens:

* Fork has no tags.
* `setuptools_scm` unable to build correct `astropy` version on fork (it is usually like 0.1.devNNNNN).
* This check below triggers outdated import on the fork CI run.

https://github.com/astropy/pytest-astropy-header/blob/53b214e433c38aee6ce43024d2d1d9540d4226ed/pytest_astropy_header/display.py#L42-L56

* This failure appears. Example log: https://github.com/pllim/astropy/runs/1408659448?check_suite_focus=true (for astropy/astropy#11052)

```
  File ".../pytest_astropy_header/display.py", line 47, in <module>
    from astropy.tests.pytest_plugins import (PYTEST_HEADER_MODULES,
ModuleNotFoundError: No module named 'astropy.tests.pytest_plugins'
```

Why we need this to work: @saimn has proposed that maybe we set up GitHub Actions to run exclusively on author's fork for `astropy` PRs instead of having them run both upstream and in the fork.

Possible solution: Drop support for `astropy<4` checks in this plugin.

**Comment by astrofrog** [comment]
Alternatively push tags to fork :)

**Comment by astrofrog** [comment]
A more serious alternative is to have a way to do the astropy>4 check in a way that doesn't depend on _version_ instead checking for the presence or absence of a given submodule.

**Comment by saimn** [comment]
> Why we need this to work: @saimn has proposed that maybe we set up GitHub Actions to run exclusively on author's fork for astropy PRs instead of having them run both upstream and in the fork.

Not on the other's fork, on the contrary actions should run only on the main repo by limiting build events in branches to `master` (and release branches):

https://github.com/saimn/sigal/blob/1084fa2c42096d6cc13c9198a91d2b344e505bbe/.github/workflows/python-tests.yml#L3-L8

I will open a PR on astropy later.

**Comment by pllim** [comment]
@saimn , sorry if I misunderstood!

**Comment by saimn** [comment]
No worries @pllim ;)

**Comment by pllim** [comment]
Also... is this really a feature then if we don't want it to run on forks? 🤔 

I think @dhomeier also asked about why it is running on forks anyway.

**Comment by dhomeier** [comment]
As I understand @saimn's patch above that would take care of it.
Looking at https://github.com/astropy/astropy/actions my understanding is that each fork is run only once before a PR is created, so the overhead is probably not significant, but it also seems quite useless. OTOH if those runs were fixed to finish the complete test suite, they _would_ consume more significant resources, and I don't really see a good purpose for that.

**Comment by saimn** [comment]
Also running on forks would not report to the PR. (Though you would probably get more parallel builds if each fork is considered independent from the main repo ;)).

**Comment by pllim** [comment]
So, should we fix this particular issue or not? Maybe it is a good thing that it fails a run on fork...
