### ISSUE TITLE
Astropy should be a required dependency

### ISSUE THREAD

**Issue by saimn** [astropy/pytest-astropy-header#33]
Ref https://github.com/astropy/pytest-astropy-header/pull/32/files#r526484941

astropy is currently an optional requirement but the plugin does nothing if astropy is not installed. 
@astrofrog - Is it to avoid a cross dependency which would confuse pip ?  

https://github.com/astropy/pytest-astropy-header/blob/e75356707a9d5f25f4a484cacfd10e68da0dee8d/setup.cfg#L28-L31

**Comment by pllim** [comment]
Maybe we should just make this plugin work without `astropy` by copying over `resolve_name`. Seems convoluted to require `astropy` and then `astropy` testing requiring this also.

https://github.com/astropy/astropy/blob/40521bf9df0630b144cf9d9d7027dba1491c5aa8/astropy/utils/introspection.py#L20

**Comment by saimn** [comment]
Indeed. Actually, looking at the use of `resolve_name`, I think we could just use `importlib.import_module` instead.
