### ISSUE TITLE
conda version

### ISSUE THREAD

**Issue by nstarman** [astropy/pytest-astropy-header#51]
I think there's an old version of this package on `conda`. With https://github.com/OpenAstronomy/github-actions-workflows, we can upload to conda simultaneously to pip.

**Comment by bsipocz** [comment]
This is a downstream issue,  the update PR is here, but it needs fixes: https://github.com/conda-forge/pytest-astropy-header-feedstock/pull/4

**Comment by mwcraig** [comment]
I have finished of the feedstock PR, so 0.2.2 should be on conda-forge soon.

**Comment by nstarman** [comment]
Thanks @mwcraig!
For the future, is it possible to automate this with https://github-actions-workflows.openastronomy.org/en/stable/publish_pure_python.html#upload-to-anaconda ?

**Comment by pllim** [comment]
@nstarman , pls open new issue for that request. Thanks!
