### ISSUE TITLE
Additional dependencies

### ISSUE THREAD

**Issue by olebole** [astropy/pytest-astropy-header#7]
There are dependencies that were not declared in `setup.cfg`:

  * numpy (`tests/test_display.py`: `import numpy`)

  * astropy (`pytest_astropy_header/display.py`: `from astropy import __version__ as astropy_version`)

Although the astropy import seems optional, the tests will fail without it; so they should at least declared as test dependency.

**Comment by astrofrog** [comment]
@olebole - yeah we definitely should mark these as test dependencies but they are not hard run time dependencies for the plugin.
